package es.vee.pdfextractor;

import com.lowagie.text.Document;
import com.lowagie.text.Paragraph;
import com.lowagie.text.rtf.RtfWriter2;
import java.awt.Color;
import java.awt.Desktop;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.filechooser.FileSystemView;

/*
 * To change this template, choose Tools | Templates and open the template in
 * the editor.
 */
/**
 *
 * @author Juan Pablo López Pulpillo <juanpablo.lopez@itc2.com>
 */
public class Main extends javax.swing.JFrame {

	private File pdfFile;
	private File rtfFile;
	private Color textColor = new Color(255, 237, 0);
	private boolean inProgress = false;

	/**
	 * Creates new form Main
	 */
	public Main() {
		initComponents();
		this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE); 
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lblPdf = new javax.swing.JLabel();
        lblRtf = new javax.swing.JLabel();
        lblTextColor = new javax.swing.JLabel();
        btnSelTextColor = new javax.swing.JButton();
        btnSelRTF = new javax.swing.JButton();
        btnSelPDF = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnExtract = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btnClose = new javax.swing.JButton();
        lblProgress = new javax.swing.JLabel();
        chkOpenWhenFinish = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PDF Extractor v.1.0");
        setBackground(new java.awt.Color(242, 243, 245));
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(242, 243, 245));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(173, 177, 178)));

        lblPdf.setBackground(new java.awt.Color(255, 255, 255));
        lblPdf.setForeground(new java.awt.Color(153, 153, 153));
        lblPdf.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPdf.setText("Seleccionar archivo PDF del que queremos extraer los resumenes");
        lblPdf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(173, 177, 178)));
        lblPdf.setOpaque(true);

        lblRtf.setBackground(new java.awt.Color(255, 255, 255));
        lblRtf.setForeground(new java.awt.Color(153, 153, 153));
        lblRtf.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRtf.setText("Archivo RTF donde se guardarán los resúmenes");
        lblRtf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(173, 177, 178)));
        lblRtf.setOpaque(true);

        lblTextColor.setBackground(new java.awt.Color(255, 237, 0));
        lblTextColor.setForeground(new java.awt.Color(153, 153, 153));
        lblTextColor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTextColor.setText("Color del texto seleccionado en el pdf");
        lblTextColor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(173, 177, 178)));
        lblTextColor.setOpaque(true);

        btnSelTextColor.setBackground(new java.awt.Color(26, 96, 142));
        btnSelTextColor.setForeground(new java.awt.Color(255, 255, 255));
        btnSelTextColor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/color_wheel.png"))); // NOI18N
        btnSelTextColor.setText("Color");
        btnSelTextColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelTextColorActionPerformed(evt);
            }
        });

        btnSelRTF.setBackground(new java.awt.Color(26, 96, 142));
        btnSelRTF.setForeground(new java.awt.Color(255, 255, 255));
        btnSelRTF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rtf.png"))); // NOI18N
        btnSelRTF.setText("RTF");
        btnSelRTF.setEnabled(false);
        btnSelRTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelRTFActionPerformed(evt);
            }
        });

        btnSelPDF.setBackground(new java.awt.Color(26, 96, 142));
        btnSelPDF.setForeground(new java.awt.Color(255, 255, 255));
        btnSelPDF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pdf.png"))); // NOI18N
        btnSelPDF.setText("PDF");
        btnSelPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelPDFActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(206, 230, 253));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(173, 177, 178)));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(206, 230, 253));

        btnExtract.setBackground(new java.awt.Color(26, 96, 142));
        btnExtract.setForeground(new java.awt.Color(255, 255, 255));
        btnExtract.setIcon(new javax.swing.ImageIcon(getClass().getResource("/process.png"))); // NOI18N
        btnExtract.setText("Extraer Resumen");
        btnExtract.setEnabled(false);
        btnExtract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExtractActionPerformed(evt);
            }
        });
        jPanel3.add(btnExtract);

        jPanel1.add(jPanel3, java.awt.BorderLayout.WEST);

        jPanel4.setBackground(new java.awt.Color(206, 230, 253));

        btnClose.setBackground(new java.awt.Color(255, 255, 255));
        btnClose.setForeground(new java.awt.Color(26, 96, 142));
        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/close.png"))); // NOI18N
        btnClose.setText("Cerrar");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        jPanel4.add(btnClose);

        jPanel1.add(jPanel4, java.awt.BorderLayout.EAST);

        lblProgress.setBackground(new java.awt.Color(206, 230, 253));
        lblProgress.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblProgress.setForeground(new java.awt.Color(39, 99, 140));
        lblProgress.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProgress.setText(" Extractor de Resúmenes de PDF");
        lblProgress.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(173, 177, 178)));
        lblProgress.setOpaque(true);

        chkOpenWhenFinish.setBackground(new java.awt.Color(153, 153, 153));
        chkOpenWhenFinish.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        chkOpenWhenFinish.setForeground(new java.awt.Color(153, 153, 153));
        chkOpenWhenFinish.setText("Abrir documento al finalizar");
        chkOpenWhenFinish.setOpaque(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblProgress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblPdf, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSelPDF, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblRtf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblTextColor, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(chkOpenWhenFinish, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnSelRTF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnSelTextColor, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblProgress, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPdf, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSelPDF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSelRTF)
                    .addComponent(lblRtf, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTextColor, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSelTextColor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkOpenWhenFinish)
                .addGap(9, 9, 9)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void btnSelTextColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelTextColorActionPerformed
		Color c = JColorChooser.showDialog(null, "Selecciona un color", lblTextColor.getBackground());
		if (c != null) {
			lblTextColor.setBackground(c);
			textColor = c;
		}
	}//GEN-LAST:event_btnSelTextColorActionPerformed

	private void btnSelPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelPDFActionPerformed

		JFileChooser fileChooser = new JFileChooser();
		FileSystemView fw = fileChooser.getFileSystemView();
		fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);

		fileChooser.setAcceptAllFileFilterUsed(false);
		fileChooser.setCurrentDirectory(fw.getDefaultDirectory());
		fileChooser.addChoosableFileFilter(new FileNameExtensionFilter("Portable Document Format", "pdf"));
		int returnVal = fileChooser.showOpenDialog(null);
		if (returnVal == JFileChooser.APPROVE_OPTION) {
			File sFile = fileChooser.getSelectedFile().getAbsoluteFile();
			boolean generate = true;
			if (sFile.exists()) {
				lblPdf.setText(sFile.getAbsolutePath());
				pdfFile = sFile;
				enableExtract();
				btnSelRTF.setEnabled(true);
			}
		}
	}//GEN-LAST:event_btnSelPDFActionPerformed

	private void enableExtract() {
		boolean enabled = (pdfFile != null && rtfFile != null);
		btnExtract.setEnabled(enabled);
	}

	private void btnSelRTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelRTFActionPerformed
		JFileChooser fileChooser = new JFileChooser();
		FileSystemView fw = fileChooser.getFileSystemView();
		fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        File defaultFile = new File(pdfFile.getName().replaceFirst(".pdf",".rtf"));
		fileChooser.setSelectedFile(defaultFile);
		fileChooser.setAcceptAllFileFilterUsed(false);
		fileChooser.setCurrentDirectory(fw.getDefaultDirectory());
		fileChooser.addChoosableFileFilter(new FileNameExtensionFilter("RTF Ricth Text Format", "rtf"));
		int returnVal = fileChooser.showSaveDialog(null);
		if (returnVal == JFileChooser.APPROVE_OPTION) {

			File sFile = null;
			if (fileChooser.getSelectedFile().getName().endsWith(".rtf")) {
				sFile = new File(fileChooser.getSelectedFile().getAbsolutePath());
			} else {
				sFile = new File(fileChooser.getSelectedFile() + ".rtf");
			}

			boolean generate = true;
			if (sFile.exists()) {
				int reply = JOptionPane.showConfirmDialog(null, "El fichero ya existe. ¿Desea substituirlo?", 
						"Reemplazar Fichero", JOptionPane.YES_NO_OPTION);
				if (reply == JOptionPane.NO_OPTION) {
					generate = false;
				}
			}
			if (generate) {
				lblRtf.setText(sFile.getAbsolutePath());
				rtfFile = sFile;
				enableExtract();
			} else {
				showErrorMessage("El fichero existe. Seleccione otro nombre de fichero.", "Error al generar el fichero rtf con los resumenes");
			}
		}
	}//GEN-LAST:event_btnSelRTFActionPerformed

	private void btnExtractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExtractActionPerformed
		changeVisibility();
		new ExtractPDFWorker().execute();
	}//GEN-LAST:event_btnExtractActionPerformed

	private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
		this.dispose();
	}//GEN-LAST:event_btnCloseActionPerformed

	private void resetForm(){

		this.pdfFile = null;
		this.rtfFile = null;
		lblPdf.setText("Seleccionar archivo PDF del que queremos extraer los resumenes");
		lblRtf.setText("Archivo RTF donde se guardarán los resúmenes");
		enableExtract();
		btnSelRTF.setEnabled(false);
		
	}

	protected class ExtractPDFWorker extends SwingWorker {

		private boolean extracted = false;

		@Override
		protected Object doInBackground() throws Exception {

			// Create Document object
			Document myDoc = new Document();
			try {
				PDFExtractor pdfExtract = PDFExtractor.create(pdfFile, textColor);
				List<PDFText> extractedTexts = pdfExtract.extract();

				RtfWriter2.getInstance(myDoc, new FileOutputStream(rtfFile));
				myDoc.open();

				for (PDFText text : extractedTexts) {
					Paragraph p = new Paragraph(text.getText());
					p.setFont(text.getFont());
					myDoc.add(p);
				}
				extracted = true;

			} catch (Exception ex) {
			} finally {
				myDoc.close();
			}

			return null;
		}

		@Override
		protected void done() {
			super.done();
			changeVisibility();
			if (extracted) {
				showMessage("Se ha generado el resumen.", "Resumen generado satisfactoriamente");
				if(chkOpenWhenFinish.isSelected()){
					try {
						Desktop dt = Desktop.getDesktop();
						dt.open(rtfFile);
					} catch (IOException ex) {
						Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
					}
				}
				
			} else {
				showErrorMessage("Se ha producido un error al generar el resumen", "Error al extraer el resumen");
			}
			resetForm();

		}
	}

	private void changeVisibility() {

		inProgress = !inProgress;

		if (inProgress) {
			lblProgress.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loader_1.GIF"))); // NOI18N
			lblProgress.setText("Extrayendo resúmen ...");

		} else {
			lblProgress.setIcon(null); // NOI18N
			lblProgress.setText("Extractor de Resúmenes de PDF");
		}

		boolean enableControls = !inProgress;
		btnSelPDF.setEnabled(enableControls);
		btnSelRTF.setEnabled(enableControls);
		btnExtract.setEnabled(enableControls);
		btnSelTextColor.setEnabled(enableControls);
	}

	private void showErrorMessage(String errorMessage, String titleMessage) {
		JOptionPane.showMessageDialog(null, errorMessage, titleMessage, JOptionPane.ERROR_MESSAGE);
	}

	private void showMessage(String message, String titleMessage) {
		JOptionPane.showMessageDialog(null, message, titleMessage, JOptionPane.PLAIN_MESSAGE);
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/*
		 * Set the Nimbus look and feel
		 */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/*
		 * Create and display the form
		 */
		java.awt.EventQueue.invokeLater(new Runnable() {

			public void run() {
				new Main().setVisible(true);
			}
		});
	}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnExtract;
    private javax.swing.JButton btnSelPDF;
    private javax.swing.JButton btnSelRTF;
    private javax.swing.JButton btnSelTextColor;
    private javax.swing.JCheckBox chkOpenWhenFinish;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblPdf;
    private javax.swing.JLabel lblProgress;
    private javax.swing.JLabel lblRtf;
    private javax.swing.JLabel lblTextColor;
    // End of variables declaration//GEN-END:variables
}
